# This is a basic workflow to help you get started with Actions

name: funny comment

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branc
  issues:
    types: [opened]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  comment:
    if: github.event_name == 'issues'
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Add funny comment 
        uses: anvitaa22/wi21-cse110-lab5@master
        id: FunnyComment
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          GIPHY_TOKEN: ${{secrets.GIPHY_TOKEN}}
          comment_type: 'gif'
